// build_weeks.js v3 — Global replace approach
const fs = require('fs');

// Word bank
const wb = [
['effort','ˈefərt','n.','努力','I will put more effort into my studies.','我会在学习上更加努力。'],
['education','ˌedʒuˈkeɪʃn','n.','教育','Education is very important.','教育非常重要。'],
['effect','ɪˈfekt','n.','影响;效果','The medicine had a good effect.','药效果很好。'],
['either','ˈiːðər','adv./conj.','也;或者','You can take either one.','你可以拿任何一个。'],
['elder','ˈeldər','adj.','年长的','My elder brother is 18.','我哥哥18岁。'],
['electric','ɪˈlektrɪk','adj.','电的','We have an electric car.','我们有一辆电动车。'],
['embarrass','ɪmˈbærəs','v.','使尴尬','Do not embarrass me.','别让我尴尬。'],
['empty','ˈempti','adj.','空的','The room is empty.','房间是空的。'],
['encourage','ɪnˈkɜːrɪdʒ','v.','鼓励','Teachers encourage students to read.','老师鼓励学生阅读。'],
['enemy','ˈenəmi','n.','敌人','He is not your enemy.','他不是你的敌人。'],
['energy','ˈenərdʒi','n.','能量;精力','I have no energy today.','我今天没有精力。'],
['engineer','ˌendʒɪˈnɪr','n.','工程师','My father is an engineer.','我爸爸是工程师。'],
['enjoy','ɪnˈdʒɔɪ','v.','享受;喜欢','I enjoy reading books.','我喜欢读书。'],
['enough','ɪˈnʌf','adj./adv.','足够的','We have enough time.','我们有足够的时间。'],
['enter','ˈentər','v.','进入','Please enter the room.','请进入房间。'],
['especially','ɪˈspeʃəli','adv.','特别;尤其','I like fruit, especially apples.','我喜欢水果，尤其是苹果。'],
['even','ˈiːvn','adv.','甚至','She did not even say goodbye.','她甚至没有说再见。'],
['event','ɪˈvent','n.','事件;活动','It was a big event.','那是一个大事件。'],
['ever','ˈevər','adv.','曾经','Have you ever been to Beijing?','你去过北京吗？'],
['every','ˈevri','adj.','每个','Every student must study hard.','每个学生都要努力学习。'],
['exact','ɪɡˈzækt','adj.','精确的','What is the exact time?','确切时间是几点？'],
['exam','ɪɡˈzæm','n.','考试','The exam is next week.','考试在下周。'],
['example','ɪɡˈzæmpl','n.','例子','Give me an example.','给我一个例子。'],
['excellent','ˈeksələnt','adj.','优秀的','Your work is excellent.','你的工作很优秀。'],
['except','ɪkˈsept','prep.','除了','Everyone came except Tom.','除了汤姆大家都来了。'],
['excite','ɪkˈsaɪt','v.','使兴奋','The news excited everyone.','这消息让所有人兴奋。'],
['excuse','ɪkˈskjuːs','n./v.','借口;原谅','Excuse me, may I come in?','打扰一下，我能进来吗？'],
['exercise','ˈeksərsaɪz','n./v.','锻炼;练习','Take more exercise every day.','每天多锻炼。'],
['expect','ɪkˈspekt','v.','期待;预料','I expect to pass the exam.','我期待通过考试。'],
['expensive','ɪkˈspensɪv','adj.','昂贵的','This watch is too expensive.','这块表太贵了。'],
['experience','ɪkˈspɪriəns','n.','经验;经历','Do you have any work experience?','你有工作经验吗？'],
['experiment','ɪkˈsperɪmənt','n.','实验','We did a science experiment.','我们做了一个科学实验。'],
['explain','ɪkˈspleɪn','v.','解释','Can you explain this to me?','你能解释这个给我吗？'],
['express','ɪkˈspres','v.','表达','Express your ideas clearly.','清楚地表达你的想法。'],
['extra','ˈekstrə','adj.','额外的','I need extra time.','我需要额外的时间。'],
['face','feɪs','n./v.','脸;面对','We must face the problem.','我们必须面对问题。'],
['fact','fækt','n.','事实','This is a scientific fact.','这是一个科学事实。'],
['fail','feɪl','v.','失败;不及格','Do not fail the exam.','别考试不及格。'],
['fair','fer','adj.','公平的','That is not fair.','这不公平。'],
['fall','fɔːl','v./n.','落下;秋天','The leaves fall in autumn.','秋天树叶落下。'],
['family','ˈfæməli','n.','家庭','Family is very important.','家庭非常重要。'],
['famous','ˈfeɪməs','adj.','著名的','He is a famous singer.','他是一位著名歌手。'],
['fan','fæn','n.','风扇;粉丝','I am a big fan of football.','我是个足球迷。'],
['far','fɑːr','adj./adv.','远的','How far is the school?','学校有多远？'],
['farm','fɑːrm','n.','农场','My grandparents live on a farm.','我爷爷奶奶住在农场。'],
['fashion','ˈfæʃn','n.','时尚','She likes fashion design.','她喜欢时尚设计。'],
['fast','fæst','adj./adv.','快的','He runs very fast.','他跑得很快。'],
['fat','fæt','adj./n.','胖的;脂肪','Eating too much makes you fat.','吃太多会让你变胖。'],
['father','ˈfɑːðər','n.','父亲','My father is a teacher.','我父亲是老师。'],
['favorite','ˈfeɪvərɪt','adj./n.','最喜欢的','This is my favorite book.','这是我最喜欢的书。'],
['fear','fɪr','n./v.','害怕','Do not fear failure.','不要害怕失败。'],
['feed','fiːd','v.','喂养','Please feed the dog.','请喂狗。'],
['feel','fiːl','v.','感觉','I feel very happy today.','我今天感觉很开心。'],
['female','ˈfiːmeɪl','adj./n.','女性的','The female singer won the prize.','那位女歌手获奖了。'],
['few','fjuː','adj.','少数的','A few students passed the test.','少数几个学生通过了考试。'],
['field','fiːld','n.','领域;田野','The children play in the field.','孩子们在田野里玩耍。'],
['fight','faɪt','v./n.','打架;争斗','Do not fight with your brother.','别和你弟弟打架。'],
['fill','fɪl','v.','填满','Please fill the glass with water.','请把杯子装满水。'],
['film','fɪlm','n.','电影','Let us watch a film tonight.','我们今晚看电影吧。'],
['final','ˈfaɪnl','adj.','最后的','This is the final exam.','这是期末考试。'],
['find','faɪnd','v.','找到','I cannot find my keys.','我找不到我的钥匙。'],
['fine','faɪn','adj.','好的;晴朗的','The weather is fine today.','今天天气很好。'],
['finish','ˈfɪnɪʃ','v.','完成','Please finish your homework.','请完成你的作业。'],
['fire','faɪər','n.','火;火灾','Do not play with fire.','不要玩火。'],
['first','fɜːrst','num./adv.','第一','First, let me introduce myself.','首先，让我介绍一下自己。'],
['fish','fɪʃ','n./v.','鱼;钓鱼','I like to eat fish.','我喜欢吃鱼。'],
['fit','fɪt','v./adj.','适合;健康的','This coat fits you well.','这件外套很适合你。'],
['fix','fɪks','v.','修理;固定','Can you fix my bike?','你能修我的自行车吗？'],
['flag','flæɡ','n.','旗帜','The red flag is waving.','红旗在飘扬。'],
['flat','flæt','adj./n.','平的;公寓','We live in a flat.','我们住在一套公寓里。'],
['flight','flaɪt','n.','航班','The flight takes two hours.','航程需要两小时。'],
['floor','flɔːr','n.','地板;楼层','The floor is very clean.','地板很干净。'],
['flower','ˈflaʊər','n.','花','I love this flower.','我喜欢这朵花。'],
['fly','flaɪ','v./n.','飞;苍蝇','Birds can fly in the sky.','鸟能在天空中飞翔。'],
['follow','ˈfɑːloʊ','v.','跟随;遵循','Please follow the rules.','请遵守规则。'],
['food','fuːd','n.','食物','Chinese food is delicious.','中国菜很好吃。'],
['foot','fʊt','n.','脚;英尺','My left foot hurts.','我的左脚疼。'],
['football','ˈfʊtbɔːl','n.','足球','He likes playing football.','他喜欢踢足球。'],
['force','fɔːrs','n./v.','力量;强迫','Do not force me to do it.','别强迫我做。'],
['foreign','ˈfɔːrən','adj.','外国的','She can speak two foreign languages.','她会说两门外语。'],
['forest','ˈfɔːrɪst','n.','森林','There are many trees in the forest.','森林里有很多树。'],
['forget','fərˈɡet','v.','忘记','Do not forget to call me.','别忘了给我打电话。'],
['forgive','fərˈɡɪv','v.','原谅','Please forgive me.','请原谅我。'],
['form','fɔːrm','n./v.','形式;形成','Please fill in the form.','请填写这个表格。'],
['forward','ˈfɔːrwərd','adv.','向前','Please move forward.','请向前移动。'],
['free','friː','adj.','自由的;免费的','Admission is free.','入场免费。'],
['fresh','freʃ','adj.','新鲜的','I want some fresh air.','我想要一些新鲜空气。'],
['friend','frend','n.','朋友','She is my best friend.','她是我最好的朋友。'],
['front','frʌnt','n./adj.','前面','Please stand in the front.','请站在前面。'],
['fruit','fruːt','n.','水果','Fruit is good for health.','水果对健康有益。'],
['full','fʊl','adj.','满的','The glass is full of water.','杯子装满了水。'],
['fun','fʌn','n./adj.','乐趣;有趣的','We had a lot of fun.','我们玩得很开心。'],
['future','ˈfjuːtʃər','n.','未来','What will you do in the future?','你将来要做什么？'],
['gain','ɡeɪn','v.','获得','You will gain experience.','你会获得经验。'],
['game','ɡeɪm','n.','游戏;比赛','Let us play a game.','我们来玩个游戏吧。'],
['garden','ˈɡɑːrdn','n.','花园','My mother grows flowers in the garden.','我妈妈在花园里种花。'],
['gate','ɡeɪt','n.','大门','Please close the gate.','请关大门。'],
['general','ˈdʒenrəl','adj.','一般的','In general, it is a good plan.','总的来说，这是个好计划。'],
['gift','ɡɪft','n.','礼物','Thank you for the gift.','谢谢你的礼物。'],
['girl','ɡɜːrl','n.','女孩','The girl is 15 years old.','那个女孩15岁。'],
['give','ɡɪv','v.','给','Please give me the book.','请给我那本书。'],
['glass','ɡlæs','n.','玻璃;杯子','Please pass me a glass of water.','请递给我一杯水。'],
['goal','ɡoʊl','n.','目标;球门','My goal is to get into a good university.','我的目标是考上好大学。'],
['gold','ɡoʊld','n./adj.','金子;金色的','She wears a gold necklace.','她戴着一条金项链。'],
['good','ɡʊd','adj.','好的','Have a good day.','祝你有美好的一天。'],
['government','ˈɡʌvərnmənt','n.','政府','The government made a new law.','政府制定了新法律。'],
['grade','ɡreɪd','n.','年级;成绩','I am in Grade 8.','我在八年级。'],
['graduate','ˈɡrædʒueɪt','v.','毕业','I will graduate next year.','我明年毕业。'],
['grammar','ˈɡræmər','n.','语法','You need to study grammar.','你需要学习语法。'],
['grandparent','ˈɡrænperənt','n.','祖父母','I visit my grandparents every week.','我每周都去看祖父母。'],
['grass','ɡræs','n.','草','Keep off the grass.','勿踏草地。'],
['great','ɡreɪt','adj.','伟大的;很棒的','You did a great job.','你做得很好。'],
['green','ɡriːn','adj./n.','绿色的','The trees are green in spring.','春天树木是绿色的。'],
['grow','ɡroʊ','v.','生长','Flowers grow in the spring.','花在春天生长。'],
['guard','ɡɑːrd','n./v.','警卫;守卫','A guard is at the gate.','门口有个警卫。'],
['guess','ɡes','v.','猜测','Can you guess the answer?','你能猜到答案吗？'],
['guest','ɡest','n.','客人','We have guests tonight.','我们今晚有客人。'],
['guide','ɡaɪd','n./v.','向导;引导','A guide showed us around.','一位导游带我们参观。'],
['habit','ˈhæbɪt','n.','习惯','Reading is a good habit.','阅读是个好习惯。'],
['hair','her','n.','头发','She has long hair.','她有一头长发。'],
['half','hæf','n./adj.','一半','I ate half of the cake.','我吃了半个蛋糕。'],
['hall','hɔːl','n.','大厅','The meeting is in the hall.','会议在大厅里。'],
['hand','hænd','n./v.','手;递给','Please hand me the pen.','请递给我笔。'],
['handle','ˈhændl','v./n.','处理;把手','Can you handle this problem?','你能处理这个问题吗？'],
['happen','ˈhæpən','v.','发生','What happened to you?','你发生了什么事？'],
['happy','ˈhæpi','adj.','快乐的','I am very happy today.','我今天很开心。'],
['hard','hɑːrd','adj./adv.','困难的;努力','Study hard and you will succeed.','努力学习你就会成功。'],
['hate','heɪt','v.','讨厌','I hate getting up early.','我讨厌早起。'],
['have','hæv','v.','有','I have a dream.','我有一个梦想。'],
['head','hed','n.','头','She nodded her head.','她点了点头。'],
['health','helθ','n.','健康','Health is more important than wealth.','健康比财富更重要。'],
['hear','hɪr','v.','听见','Can you hear me?','你能听见我吗？'],
['heart','hɑːrt','n.','心脏;内心','Listen to your heart.','听从你的内心。'],
['heat','hiːt','n./v.','热;加热','Heat the water for tea.','把水加热泡茶。'],
['heavy','ˈhevi','adj.','重的','This box is too heavy.','这个箱子太重了。'],
['help','help','v./n.','帮助','Can you help me?','你能帮我吗？'],
['hero','ˈhɪroʊ','n.','英雄','He is a national hero.','他是一个民族英雄。'],
['hide','haɪd','v.','隐藏','Where did you hide the key?','你把钥匙藏哪了？'],
['high','haɪ','adj.','高的','The mountain is very high.','那座山非常高。'],
['hill','hɪl','n.','小山','We climbed the hill.','我们爬了小山。'],
['history','ˈhɪstri','n.','历史','History is my favorite subject.','历史是我最喜欢的科目。'],
['hit','hɪt','v.','撞击;打','He hit the ball very hard.','他用力打球。'],
['hobby','ˈhɑːbi','n.','爱好','My hobby is reading.','我的爱好是阅读。'],
['hold','hoʊld','v.','握住;举办','Hold my hand.','握住我的手。'],
['hole','hoʊl','n.','洞','There is a hole in the wall.','墙上有个洞。'],
['holiday','ˈhɑːlədeɪ','n.','假期','Where did you go on holiday?','你假期去哪了？'],
['home','hoʊm','n.','家','I want to go home.','我想回家。'],
['homework','ˈhoʊmwɜːrk','n.','家庭作业','Have you finished your homework?','你做完作业了吗？'],
['honest','ˈɑːnɪst','adj.','诚实的','Be honest with me.','对我诚实。'],
['hope','hoʊp','v./n.','希望','I hope you pass the exam.','我希望你通过考试。'],
['horse','hɔːrs','n.','马','He can ride a horse.','他会骑马。'],
['hospital','ˈhɑːspɪtl','n.','医院','He was taken to the hospital.','他被送到医院。'],
['hot','hɑːt','adj.','热的','It is very hot in summer.','夏天非常热。'],
['hotel','hoʊˈtel','n.','旅馆','We stayed at a nice hotel.','我们住在一个不错的旅馆。'],
['hour','aʊər','n.','小时','Wait for me for an hour.','等我一个小时。'],
['house','haʊs','n.','房子','We live in a big house.','我们住在一个大房子里。'],
['human','ˈhjuːmən','n./adj.','人类;人的','To err is human.','人非圣贤，孰能无过。'],
['hungry','ˈhʌŋɡri','adj.','饥饿的','I am very hungry.','我很饿。'],
['hurry','ˈhɜːri','v./n.','赶快','Hurry up! We are late.','快点！我们迟到了。'],
['hurt','hɜːrt','v.','伤害;疼','My head hurts.','我头疼。'],
['husband','ˈhʌzbənd','n.','丈夫','Her husband is a doctor.','她丈夫是医生。'],
['idea','aɪˈdiːə','n.','主意;想法','That is a good idea.','那是个好主意。'],
['ill','ɪl','adj.','生病的','She is ill in bed.','她卧病在床。'],
['imagine','ɪˈmædʒɪn','v.','想象','Imagine a better future.','想象一个更好的未来。'],
['impossible','ɪmˈpɑːsəbl','adj.','不可能的','Nothing is impossible.','没有什么是不可能的。'],
['improve','ɪmˈpruːv','v.','改进;提高','You need to improve your English.','你需要提高英语。'],
['include','ɪnˈkluːd','v.','包括','The price includes lunch.','价格包括午餐。'],
['increase','ɪnˈkriːs','v.','增加','The population is increasing.','人口在增长。'],
['industry','ˈɪndəstri','n.','工业;行业','The car industry is growing.','汽车工业在增长。'],
['influence','ˈɪnfluəns','n./v.','影响','He has a great influence on me.','他对我影响很大。'],
['information','ˌɪnfərˈmeɪʃn','n.','信息','Can you give me some information?','你能给我一些信息吗？'],
['insist','ɪnˈsɪst','v.','坚持','I insist on doing it.','我坚持要做。'],
['instead','ɪnˈsted','adv.','代替;反而','Let us go to the park instead.','我们去公园吧。'],
['instruction','ɪnˈstrʌkʃn','n.','指令;说明','Follow the instructions carefully.','仔细按照说明操作。'],
['interest','ˈɪntrəst','n.','兴趣;利息','I have a great interest in music.','我对音乐很感兴趣。'],
['international','ˌɪntərˈnæʃnəl','adj.','国际的','English is an international language.','英语是国际语言。'],
['introduce','ˌɪntrəˈduːs','v.','介绍','Let me introduce myself.','让我介绍一下自己。'],
['invent','ɪnˈvent','v.','发明','Who invented the telephone?','谁发明了电话？'],
['invite','ɪnˈvaɪt','v.','邀请','I invite you to my party.','我邀请你来我的聚会。'],
['island','ˈaɪlənd','n.','岛屿','Hainan is a beautiful island.','海南是个美丽的岛屿。'],
['jacket','ˈdʒækɪt','n.','夹克;外套','Put on your jacket. It is cold.','穿上外套，天很冷。'],
['job','dʒɑːb','n.','工作','She found a new job.','她找到了新工作。'],
['join','dʒɔɪn','v.','加入','Join us for dinner.','和我们一起吃饭吧。'],
['joke','dʒoʊk','n.','笑话','He told a joke.','他讲了一个笑话。'],
['journey','ˈdʒɜːrni','n.','旅程','The journey took three hours.','旅程花了三小时。'],
['joy','dʒɔɪ','n.','快乐','She jumped for joy.','她高兴得跳了起来。'],
['juice','dʒuːs','n.','果汁','I want a glass of orange juice.','我想要一杯橙汁。'],
['jump','dʒʌmp','v.','跳','The cat jumped over the wall.','猫跳过了墙。'],
['junior','ˈdʒuːniər','adj.','初级的','She is a junior high student.','她是个初中生。'],
['just','dʒʌst','adv.','刚刚;只是','I just arrived home.','我刚到家。'],
['keen','kiːn','adj.','热衷的','She is keen on music.','她热衷音乐。'],
['keep','kiːp','v.','保持;保留','Keep quiet in the library.','在图书馆保持安静。'],
['key','kiː','n.','钥匙;关键','Hard work is the key to success.','努力是成功的关键。'],
['kick','kɪk','v.','踢','He kicked the ball.','他踢了球。'],
['kid','kɪd','n.','小孩','The kids are playing outside.','小孩在外面玩。'],
['kind','kaɪnd','adj./n.','善良的;种类','She is very kind to others.','她对别人很善良。'],
['king','kɪŋ','n.','国王','The king ruled the country.','国王统治国家。'],
['kitchen','ˈkɪtʃɪn','n.','厨房','My mother is cooking in the kitchen.','我妈妈在厨房做饭。'],
['knee','niː','n.','膝盖','He hurt his knee.','他伤了膝盖。'],
['knife','naɪf','n.','刀','Be careful with the knife.','小心用刀。'],
['know','noʊ','v.','知道','I know the answer.','我知道答案。'],
['knowledge','ˈnɑːlɪdʒ','n.','知识','Knowledge is power.','知识就是力量。'],
['lack','læk','n./v.','缺乏','I lack confidence.','我缺乏自信。'],
['lady','ˈleɪdi','n.','女士','She is a very nice lady.','她是一位很好的女士。'],
['lake','leɪk','n.','湖','We went boating on the lake.','我们去湖上划船。'],
['land','lænd','n.','土地','The land is very fertile.','这片土地很肥沃。'],
['language','ˈlæŋɡwɪdʒ','n.','语言','Learning a new language is fun.','学一门新语言很有趣。'],
['large','lɑːrdʒ','adj.','大的','China is a large country.','中国是个大国。'],
['last','læst','adj./v.','最后的;持续','Last weekend I visited my aunt.','上周末我去看了姑妈。'],
['late','leɪt','adj.','迟到的','Do not be late for school.','上学别迟到。'],
['later','ˈleɪtər','adv.','后来;稍后','I will call you later.','我稍后给你打电话。'],
['laugh','læf','v.','大笑','Do not laugh at others.','不要嘲笑别人。'],
['law','lɔː','n.','法律','We must obey the law.','我们必须遵守法律。'],
['lazy','ˈleɪzi','adj.','懒惰的','He is too lazy to do homework.','他太懒了不做作业。'],
['lead','liːd','v.','带领','He will lead the team.','他将带领团队。'],
['learn','lɜːrn','v.','学习','I want to learn to swim.','我想学游泳。'],
['least','liːst','adj./adv.','最小的;最少','At least try your best.','至少尽你最大努力。'],
['leave','liːv','v.','离开','What time do you leave for school?','你几点去上学？'],
['left','left','adj./n.','左边的;左边','Turn left at the corner.','在拐角处左转。'],
['lend','lend','v.','借出','Can you lend me your pen?','你能借我你的笔吗？'],
['lesson','ˈlesn','n.','课;教训','We have an English lesson today.','今天我们有一节英语课。'],
['let','let','v.','让','Let me help you.','让我帮你。'],
['library','ˈlaɪbreri','n.','图书馆','We study in the library.','我们在图书馆学习。'],
['lie','laɪ','v.','躺;说谎','Do not lie to me.','别对我撒谎。'],
['life','laɪf','n.','生活;生命','Life is beautiful.','生活是美好的。'],
['lift','lɪft','v.','举起','Can you lift this box?','你能举起这个箱子吗？'],
['light','laɪt','n./adj.','光;轻的','Turn on the light.','把灯打开。'],
['like','laɪk','v./prep.','喜欢;像','I like playing basketball.','我喜欢打篮球。'],
['line','laɪn','n.','线;排','Please stand in line.','请排队。'],
['list','lɪst','n.','清单','Make a shopping list.','写一个购物清单。'],
['listen','ˈlɪsn','v.','听','Listen to me carefully.','仔细听我说。'],
['little','ˈlɪtl','adj.','小的;少的','I have a little money.','我有一点钱。'],
['live','lɪv','v.','居住;活着','I live in Beijing.','我住在北京。'],
['local','ˈloʊkl','adj.','当地的','Let us try the local food.','我们尝尝当地的食物吧。'],
['lock','lɑːk','v./n.','锁','Please lock the door.','请锁门。'],
['lonely','ˈloʊnli','adj.','孤独的','She feels lonely.','她感到孤独。'],
['long','lɔːŋ','adj.','长的','It is a long story.','说来话长。'],
['look','lʊk','v.','看','Look at the blackboard.','看黑板。'],
['lose','luːz','v.','失去;输','Do not lose hope.','不要失去希望。'],
['lot','lɑːt','n.','许多','I have a lot of homework.','我有很多作业。'],
['love','lʌv','v./n.','爱','I love my family.','我爱我家。'],
['low','loʊ','adj.','低的','The temperature is low today.','今天温度很低。'],
['luck','lʌk','n.','运气','Good luck with your exam!','祝你考试好运！'],
['machine','məˈʃiːn','n.','机器','This machine is very useful.','这台机器很有用。'],
['mad','mæd','adj.','生气的;疯狂的','Do not be mad at me.','别生我的气。'],
['main','meɪn','adj.','主要的','What is the main reason?','主要原因是什么？'],
['make','meɪk','v.','制作;使','Let us make a cake.','我们做个蛋糕吧。'],
['manage','ˈmænɪdʒ','v.','管理;设法','Can you manage it?','你能搞定吗？'],
['many','ˈmeni','adj.','许多的','Many students passed the exam.','许多学生通过了考试。'],
['mark','mɑːrk','n./v.','标记;分数','He got a high mark.','他得了高分。'],
['market','ˈmɑːrkɪt','n.','市场','I go to the market every morning.','我每天早上都去市场。'],
['marry','ˈmæri','v.','结婚','They plan to marry next year.','他们计划明年结婚。'],
['master','ˈmæstər','n./v.','大师;掌握','Practice makes a master.','熟能生巧。'],
['match','mætʃ','n./v.','比赛;匹配','We won the football match.','我们赢了足球比赛。'],
['matter','ˈmætər','n./v.','事情;要紧','What is the matter?','怎么了？'],
['maybe','ˈmeɪbi','adv.','也许','Maybe it will rain tomorrow.','也许明天会下雨。'],
['meal','miːl','n.','餐;一顿饭','We have three meals a day.','我们一天吃三餐。'],
['mean','miːn','v.','意思是','What do you mean?','你是什么意思？'],
['meaning','ˈmiːnɪŋ','n.','意思','What is the meaning of this word?','这个词是什么意思？'],
['measure','ˈmeʒər','v.','测量','Measure the length of the table.','测量桌子的长度。'],
['meat','miːt','n.','肉','I do not eat meat.','我不吃肉。'],
['medicine','ˈmedɪsn','n.','药;医学','Take this medicine three times a day.','这个药一天吃三次。'],
['meet','miːt','v.','遇见;见面','Nice to meet you.','很高兴见到你。'],
['member','ˈmembər','n.','成员','He is a member of the team.','他是团队的一员。'],
['memory','ˈmeməri','n.','记忆','I have a good memory.','我记性很好。'],
['message','ˈmesɪdʒ','n.','消息;信息','Can I take a message?','要我捎个口信吗？'],
['method','ˈmeθəd','n.','方法','What is the best method?','最好的方法是什么？'],
['middle','ˈmɪdl','n./adj.','中间','She sits in the middle.','她坐在中间。'],
['mile','maɪl','n.','英里','The station is two miles away.','车站在两英里外。'],
['milk','mɪlk','n.','牛奶','Drink a glass of milk every day.','每天喝一杯牛奶。'],
['mind','maɪnd','n./v.','头脑;介意','Do you mind if I smoke?','你介意我抽烟吗？'],
['mine','maɪn','pron.','我的','This book is mine.','这本书是我的。'],
['minute','ˈmɪnɪt','n.','分钟','Wait a minute.','等一下。'],
['miss','mɪs','v.','错过;想念','I miss my family.','我想我的家人。'],
['mistake','mɪˈsteɪk','n.','错误','Everyone makes mistakes.','每个人都会犯错。'],
['model','ˈmɑːdl','n.','模型;模特','He is a fashion model.','他是个时装模特。'],
['modern','ˈmɑːdərn','adj.','现代的','We live in a modern society.','我们生活在现代社会。'],
['moment','ˈmoʊmənt','n.','时刻','Wait a moment.','等一下。'],
['money','ˈmʌni','n.','钱','Money cannot buy happiness.','金钱买不到幸福。'],
['monitor','ˈmɑːnɪtər','n.','显示器;班长','He is the class monitor.','他是班长。'],
['month','mʌnθ','n.','月','Next month is July.','下个月是七月。'],
['mood','muːd','n.','心情','I am in a good mood.','我心情很好。'],
['moon','muːn','n.','月亮','The moon is bright tonight.','今晚月亮很亮。'],
['morning','ˈmɔːrnɪŋ','n.','早上','Good morning, teacher.','老师早上好。'],
['most','moʊst','adj./adv.','最多的','Most students enjoy sports.','大多数学生喜欢运动。'],
['mother','ˈmʌðər','n.','母亲','My mother is a nurse.','我妈妈是护士。'],
['mountain','ˈmaʊntn','n.','山','We climbed the mountain.','我们爬了那座山。'],
['move','muːv','v.','移动','Move the chair, please.','请移动椅子。'],
['movie','ˈmuːvi','n.','电影','Let us see a movie.','我们去看电影吧。'],
['much','mʌtʃ','adj./adv.','很多','Thank you very much.','非常感谢。'],
['museum','mjuˈziːəm','n.','博物馆','We visited the museum.','我们参观了博物馆。'],
['music','ˈmjuːzɪk','n.','音乐','I listen to music every day.','我每天听音乐。'],
['must','mʌst','aux.','必须','You must study hard.','你必须努力学习。'],
['name','neɪm','n.','名字','What is your name?','你叫什么名字？'],
['nation','ˈneɪʃn','n.','国家;民族','China is a great nation.','中国是个伟大的国家。'],
['natural','ˈnætʃrəl','adj.','自然的','It is natural to feel scared.','感到害怕是自然的。'],
['nature','ˈneɪtʃər','n.','自然','I love nature.','我热爱大自然。'],
['near','nɪr','adj./prep.','近的','The school is near my home.','学校在我家附近。'],
['necessary','ˈnesəseri','adj.','必要的','Water is necessary for life.','水是生命必需的。'],
['need','niːd','v./n.','需要','I need your help.','我需要你的帮助。'],
['neighbor','ˈneɪbər','n.','邻居','Our neighbors are friendly.','我们的邻居很友好。'],
['nervous','ˈnɜːrvəs','adj.','紧张的','I am nervous about the test.','我对考试感到紧张。'],
['never','ˈnevər','adv.','从不','I have never been to Japan.','我从没去过日本。'],
['new','nuː','adj.','新的','I bought a new book.','我买了本新书。'],
['news','nuːz','n.','新闻','Have you heard the news?','你听说那个新闻了吗？'],
['newspaper','ˈnuːzpeɪpər','n.','报纸','My father reads the newspaper.','我爸爸看报纸。'],
['next','nekst','adj./adv.','下一个','See you next week.','下周见。'],
['nice','naɪs','adj.','好的;友好的','You look nice today.','你今天看起来很棒。'],
['night','naɪt','n.','夜晚','Good night and sweet dreams.','晚安，好梦。'],
['noise','nɔɪz','n.','噪音','Do not make noise.','不要制造噪音。'],
['none','nʌn','pron.','一个也没有','None of them came.','他们一个也没来。'],
['normal','ˈnɔːrml','adj.','正常的','Everything is normal.','一切正常。'],
['north','nɔːrθ','n.','北方','Beijing is in the north.','北京在北方。'],
['note','noʊt','n./v.','笔记;注意','Take notes in class.','上课要做笔记。'],
['novel','ˈnɑːvl','n.','小说','I am reading a novel.','我在读一本小说。'],
['number','ˈnʌmbər','n.','数字;号码','What is your phone number?','你的电话号码是多少？'],
['nurse','nɜːrs','n.','护士','The nurse is very kind.','那位护士很善良。'],
['ocean','ˈoʊʃn','n.','海洋','The ocean is very deep.','海洋很深。'],
['offer','ˈɑːfər','v.','提供','He offered to help me.','他主动提出帮我。'],
['office','ˈɑːfɪs','n.','办公室','He works in an office.','他在办公室工作。'],
['often','ˈɔːfn','adv.','经常','I often go to the library.','我经常去图书馆。'],
['oil','ɔɪl','n.','油','Cook the fish in oil.','用油煎鱼。'],
['once','wʌns','adv.','一次;曾经','I go swimming once a week.','我每周游泳一次。'],
['only','ˈoʊnli','adv./adj.','只;唯一的','I am the only child.','我是独生子。'],
['open','ˈoʊpən','v./adj.','打开;开放的','Open the window, please.','请开窗。'],
['opinion','əˈpɪnjən','n.','意见','What is your opinion?','你的意见是什么？'],
['opportunity','ˌɑːpərˈtuːnəti','n.','机会','This is a great opportunity.','这是个好机会。'],
['opposite','ˈɑːpəzɪt','adj./n.','相反的;对面','The school is opposite the park.','学校在公园对面。'],
['order','ˈɔːrdər','n./v.','顺序;命令','Are you ready to order?','你准备好点菜了吗？'],
['ordinary','ˈɔːrdneri','adj.','普通的','He is an ordinary student.','他是个普通学生。'],
['organize','ˈɔːrɡənaɪz','v.','组织','Let us organize a party.','我们组织一个派对吧。'],
['other','ˈʌðər','adj.','其他的','Do you have any other questions?','你还有其他问题吗？'],
['out','aʊt','adv.','出去','Let us go out for a walk.','我们出去散步吧。'],
['outside','ˌaʊtˈsaɪd','prep./adv.','在外面','It is cold outside.','外面很冷。'],
['over','ˈoʊvər','prep./adv.','超过;在上方','The game is over.','游戏结束了。'],
['own','oʊn','adj./v.','自己的;拥有','I have my own room.','我有自己的房间。'],
['pack','pæk','v.','打包','Pack your bags. We are leaving.','打包行李，我们要走了。'],
['page','peɪdʒ','n.','页','Turn to page 20.','翻到第20页。'],
['pain','peɪn','n.','疼痛','I have a pain in my back.','我背疼。'],
['paint','peɪnt','v./n.','画画;油漆','She likes to paint.','她喜欢画画。'],
['pair','per','n.','一双;一对','I need a pair of shoes.','我需要一双鞋。'],
['paper','ˈpeɪpər','n.','纸;论文','Please hand in your paper.','请交论文。'],
['pardon','ˈpɑːrdn','n./v.','原谅','I beg your pardon.','请再说一遍。'],
['parent','ˈperənt','n.','父母','My parents are teachers.','我父母是老师。'],
['park','pɑːrk','n./v.','公园;停车','Let us go to the park.','我们去公园吧。'],
['part','pɑːrt','n.','部分;角色','Which part do you like best?','你最喜欢哪部分？'],
['party','ˈpɑːrti','n.','聚会;党派','We had a great party.','我们开了个很棒的派对。'],
['pass','pæs','v.','通过;传递','Please pass me the salt.','请把盐递给我。'],
['passage','ˈpæsɪdʒ','n.','段落;通道','Read the following passage.','读下面的段落。'],
['passenger','ˈpæsɪndʒər','n.','乘客','The bus is full of passengers.','公交车挤满了乘客。'],
['past','pæst','adj./n.','过去的','Do not live in the past.','不要活在过去。'],
['patient','ˈpeɪʃnt','n./adj.','病人;耐心的','Be patient with yourself.','对自己要有耐心。'],
['pay','peɪ','v.','支付','How much did you pay?','你付了多少钱？'],
['peace','piːs','n.','和平','We all want peace.','我们都想要和平。'],
['perfect','ˈpɜːrfɪkt','adj.','完美的','Nobody is perfect.','没有人是完美的。'],
['perform','pərˈfɔːrm','v.','表演;表现','She performed very well.','她表现得很好。'],
['perhaps','pərˈhæps','adv.','也许','Perhaps we should go now.','也许我们现在该走了。'],
['person','ˈpɜːrsn','n.','人','She is a kind person.','她是个善良的人。'],
['personal','ˈpɜːrsənl','adj.','个人的','This is my personal opinion.','这是我个人意见。'],
['pet','pet','n.','宠物','I have a pet dog.','我有一只宠物狗。'],
['photo','ˈfoʊtoʊ','n.','照片','Take a photo of us.','给我们拍张照片。'],
['physics','ˈfɪzɪks','n.','物理','Physics is my favorite subject.','物理是我最喜欢的科目。'],
['piano','piˈænoʊ','n.','钢琴','She plays the piano very well.','她钢琴弹得很好。'],
['pick','pɪk','v.','挑选;捡起','Pick up the trash.','捡起垃圾。'],
['picnic','ˈpɪknɪk','n.','野餐','Let us go for a picnic.','我们去野餐吧。'],
['picture','ˈpɪktʃər','n.','图片;照片','Look at this picture.','看这张照片。'],
['piece','piːs','n.','一片;一块','Give me a piece of cake.','给我一块蛋糕。'],
['pilot','ˈpaɪlət','n.','飞行员','He wants to be a pilot.','他想当飞行员。'],
['pity','ˈpɪti','n./v.','遗憾;同情','What a pity!','真遗憾！'],
['place','pleɪs','n.','地方','This is a beautiful place.','这是个美丽的地方。'],
['plan','plæn','n./v.','计划','What is your plan?','你的计划是什么？'],
['plane','pleɪn','n.','飞机','The plane takes off at 8 AM.','飞机早上8点起飞。'],
['plant','plænt','n.','植物','Water the plants every day.','每天给植物浇水。'],
['play','pleɪ','v.','玩;播放','Let us play together.','我们一起玩吧。'],
['pleasant','ˈpleznt','adj.','令人愉快的','We had a pleasant evening.','我们度过了一个愉快的夜晚。'],
['pleasure','ˈpleʒər','n.','快乐;乐趣','It is a pleasure to meet you.','很高兴见到你。'],
['plenty','ˈplenti','n.','大量;充足','We have plenty of time.','我们有充足的时间。'],
['pocket','ˈpɑːkɪt','n.','口袋','He put the key in his pocket.','他把钥匙放进口袋。'],
['point','pɔɪnt','n./v.','点;指向','What is your point?','你的观点是什么？'],
['police','pəˈliːs','n.','警察','Call the police right now.','马上报警。'],
['polite','pəˈlaɪt','adj.','有礼貌的','You should be polite to elders.','你应该对长辈有礼貌。'],
['pollute','pəˈluːt','v.','污染','Cars pollute the air.','汽车污染空气。'],
['pool','puːl','n.','游泳池','Let us swim in the pool.','我们去游泳池游泳吧。'],
['poor','pʊr','adj.','贫穷的;差的','He came from a poor family.','他来自一个贫穷的家庭。'],
['popular','ˈpɑːpjələr','adj.','受欢迎的','This song is very popular.','这首歌很受欢迎。'],
['population','ˌpɑːpjuˈleɪʃn','n.','人口','What is the population of China?','中国的人口是多少？'],
['possible','ˈpɑːsəbl','adj.','可能的','Is it possible to finish today?','今天能完成吗？'],
['post','poʊst','n./v.','邮寄;岗位','Please post this letter for me.','请帮我把这封信寄了。'],
['potato','pəˈteɪtoʊ','n.','土豆','I like fried potatoes.','我喜欢炸土豆。'],
['pound','paʊnd','n.','英镑;磅','It costs five pounds.','它要五英镑。'],
['power','ˈpaʊər','n.','力量;权力','Knowledge is power.','知识就是力量。'],
['practice','ˈpræktɪs','n./v.','练习','Practice makes perfect.','熟能生巧。'],
['praise','preɪz','v./n.','赞扬','The teacher praised his work.','老师表扬了他的作业。'],
['prepare','prɪˈper','v.','准备','Prepare for the exam.','为考试做准备。'],
['present','ˈpreznt','n./adj.','礼物;现在的','Thank you for the present.','谢谢你的礼物。'],
['president','ˈprezɪdənt','n.','总统;主席','He became the president.','他成为了总统。'],
['press','pres','v.','按;压','Press the button to start.','按按钮开始。'],
['pretend','prɪˈtend','v.','假装','Do not pretend to be sick.','别假装生病。'],
['pretty','ˈprɪti','adj./adv.','漂亮的;相当','She looks very pretty.','她看起来很漂亮。'],
['prevent','prɪˈvent','v.','阻止;预防','Prevent accidents from happening.','防止事故发生。'],
['price','praɪs','n.','价格','What is the price of this book?','这本书的价格是多少？'],
['pride','praɪd','n.','自豪;骄傲','She takes pride in her work.','她为自己的工作感到自豪。'],
['primary','ˈpraɪmeri','adj.','初级的;主要的','Primary education is important.','小学教育很重要。'],
['print','prɪnt','v.','打印;印刷','Please print this document.','请打印这份文件。'],
['prison','ˈprɪzn','n.','监狱','He was sent to prison.','他被送进了监狱。'],
['private','ˈpraɪvət','adj.','私人的','This is my private room.','这是我的私人房间。'],
['prize','praɪz','n.','奖品;奖金','She won the first prize.','她赢得了一等奖。'],
['probably','ˈprɑːbəbli','adv.','大概;很可能','It will probably rain tomorrow.','明天很可能会下雨。'],
['problem','ˈprɑːbləm','n.','问题;难题','What is the problem?','是什么问题？'],
['produce','prəˈduːs','v.','生产;制造','This factory produces cars.','这个工厂生产汽车。'],
['program','ˈproʊɡræm','n.','节目;程序','What is your favorite TV program?','你最喜欢的电视节目是什么？'],
['progress','ˈprɑːɡres','n.','进步','You have made great progress.','你取得了很大进步。'],
['promise','ˈprɑːmɪs','v./n.','承诺','I promise to help you.','我承诺会帮你。'],
['pronounce','prəˈnaʊns','v.','发音','How do you pronounce this word?','这个词怎么发音？'],
['proper','ˈprɑːpər','adj.','适当的','Is this the proper way?','这是正确的方法吗？'],
['protect','prəˈtekt','v.','保护','We must protect the environment.','我们必须保护环境。'],
['proud','praʊd','adj.','自豪的','I am proud of you.','我为你感到自豪。'],
['prove','pruːv','v.','证明','Can you prove it?','你能证明吗？'],
['provide','prəˈvaɪd','v.','提供','The school provides free lunch.','学校提供免费午餐。'],
['public','ˈpʌblɪk','adj./n.','公共的;公众','Public speaking is difficult.','公开演讲很难。'],
['pull','pʊl','v.','拉;拖','Pull the door to open it.','拉门把它打开。'],
['punish','ˈpʌnɪʃ','v.','惩罚','Do not punish the child.','不要惩罚孩子。'],
['pupil','ˈpjuːpl','n.','学生','There are 30 pupils in the class.','班上有30个学生。'],
['purpose','ˈpɜːrpəs','n.','目的','What is the purpose of this meeting?','这次会议的目的是什么？'],
['push','pʊʃ','v.','推','Push the door, please.','请推门。'],
['quarter','ˈkwɔːrtər','n.','四分之一;一刻钟','It is a quarter past three.','现在是三点一刻。'],
['queen','kwiːn','n.','女王;王后','The queen visited our city.','女王访问了我们的城市。'],
['question','ˈkwestʃən','n.','问题','Do you have any questions?','你有什么问题吗？'],
['quick','kwɪk','adj.','快的','Be quick, we are late.','快点，我们要迟到了。'],
['quiet','ˈkwaɪət','adj.','安静的','Please keep quiet.','请保持安静。'],
['quite','kwaɪt','adv.','相当;很','It is quite cold today.','今天相当冷。'],
['rabbit','ˈræbɪt','n.','兔子','The rabbit runs very fast.','兔子跑得很快。'],
['race','reɪs','n.','比赛;种族','He won the race.','他赢得了比赛。'],
['radio','ˈreɪdioʊ','n.','收音机','I listen to the radio every morning.','我每天早上听收音机。'],
['railway','ˈreɪlweɪ','n.','铁路','The railway connects the two cities.','铁路连接了两个城市。'],
['rain','reɪn','n./v.','雨;下雨','It is raining outside.','外面在下雨。'],
['raise','reɪz','v.','举起;提高','Raise your hand, please.','请举手。'],
['rapid','ˈræpɪd','adj.','迅速的','He made rapid progress.','他进步很快。'],
['rather','ˈræðər','adv.','宁愿;相当','I would rather stay at home.','我宁愿待在家里。'],
['reach','riːtʃ','v.','到达;够到','Can you reach the top shelf?','你能够到最上面的架子吗？'],
['ready','ˈredi','adj.','准备好的','Are you ready to go?','你准备好出发了吗？'],
['real','ˈriːəl','adj.','真实的','Is this story real?','这个故事是真的吗？'],
['realize','ˈriːəlaɪz','v.','意识到;实现','I realized my mistake.','我意识到了我的错误。'],
['really','ˈriːəli','adv.','真正地','I really like this book.','我真的很喜欢这本书。'],
['reason','ˈriːzn','n.','原因','What is the reason for your absence?','你缺席的原因是什么？'],
['receive','rɪˈsiːv','v.','收到','I received your letter yesterday.','我昨天收到了你的信。'],
['recent','ˈriːsnt','adj.','最近的','Have you read recent news?','你看了最近的新闻吗？'],
['record','ˈrekərd','n./v.','记录;录音','Keep a record of your progress.','记录你的进步。'],
['recycle','ˌriːˈsaɪkl','v.','回收','We should recycle waste paper.','我们应该回收废纸。'],
['reduce','rɪˈduːs','v.','减少','We need to reduce pollution.','我们需要减少污染。'],
['refuse','rɪˈfjuːz','v.','拒绝','He refused to answer.','他拒绝回答。'],
['regret','rɪˈɡret','v.','后悔','I regret saying that.','我后悔说了那些话。'],
['relation','rɪˈleɪʃn','n.','关系','We have a good relation.','我们有良好的关系。'],
['relative','ˈrelətɪv','n.','亲戚','My relatives came to visit.','我的亲戚来拜访了。'],
['remain','rɪˈmeɪn','v.','保持;剩余','Please remain seated.','请保持坐姿。'],
['remember','rɪˈmembər','v.','记得','Do you remember me?','你记得我吗？'],
['remind','rɪˈmaɪnd','v.','提醒','Remind me to call her.','提醒我给她打电话。'],
['remove','rɪˈmuːv','v.','移除','Remove the old furniture.','把旧家具搬走。'],
['repair','rɪˈper','v.','修理','Can you repair my watch?','你能修我的手表吗？'],
['repeat','rɪˈpiːt','v.','重复','Please repeat after me.','请跟我重复。'],
['reply','rɪˈplaɪ','v.','回复','Please reply to my email.','请回复我的邮件。'],
['report','rɪˈpɔːrt','n./v.','报告','Write a report about the trip.','写一篇关于这次旅行的报告。'],
['require','rɪˈkwaɪər','v.','需要;要求','This job requires patience.','这份工作需要耐心。'],
['research','rɪˈsɜːrtʃ','n.','研究','He is doing medical research.','他在做医学研究。'],
['respect','rɪˈspekt','v./n.','尊重','We should respect the elderly.','我们应该尊重老人。'],
['rest','rest','n./v.','休息','Take a rest after lunch.','午饭后休息一下。'],
['restaurant','ˈrestrɑːnt','n.','餐厅','Let us eat at a restaurant.','我们去餐厅吃饭吧。'],
['result','rɪˈzʌlt','n.','结果','The result was surprising.','结果令人惊讶。'],
['return','rɪˈtɜːrn','v.','返回','When will you return?','你什么时候回来？'],
['review','rɪˈvjuː','v./n.','复习;回顾','Review your notes before the test.','考试前复习你的笔记。'],
['rich','rɪtʃ','adj.','富有的','He is a rich businessman.','他是个富有的商人。'],
['ride','raɪd','v.','骑;乘','Can you ride a bike?','你会骑自行车吗？'],
['right','raɪt','adj./n.','正确的;右边','You are right.','你是对的。'],
['ring','rɪŋ','v./n.','响铃;戒指','The phone is ringing.','电话在响。'],
['rise','raɪz','v.','升起;上升','The sun rises in the east.','太阳从东方升起。'],
['risk','rɪsk','n.','风险','Do not take unnecessary risks.','不要冒不必要的风险。'],
['river','ˈrɪvər','n.','河流','The river flows to the sea.','河流流向大海。'],
['road','roʊd','n.','道路','Cross the road carefully.','小心过马路。'],
['robot','ˈroʊbɑːt','n.','机器人','A robot can do many things.','机器人可以做很多事情。'],
['rock','rɑːk','n.','岩石','He sat on a big rock.','他坐在一块大石头上。'],
['role','roʊl','n.','角色;作用','What is your role in the team?','你在团队中是什么角色？'],
['room','ruːm','n.','房间','This is my room.','这是我的房间。'],
['rope','roʊp','n.','绳子','Tie it with a rope.','用绳子把它绑起来。'],
['rose','roʊz','n.','玫瑰','She gave me a red rose.','她给了我一朵红玫瑰。'],
['round','raʊnd','adj./adv.','圆的;在周围','The earth is round.','地球是圆的。'],
['row','roʊ','n./v.','一排;划船','Sit in the front row.','坐在第一排。'],
['rubbish','ˈrʌbɪʃ','n.','垃圾','Do not throw rubbish everywhere.','不要到处扔垃圾。'],
['rule','ruːl','n.','规则','Follow the rules.','遵守规则。'],
['ruler','ˈruːlər','n.','尺子;统治者','Use a ruler to draw a line.','用尺子画一条线。'],
['run','rʌn','v.','跑步','I run every morning.','我每天早上跑步。'],
['rush','rʌʃ','v.','冲;匆忙','Do not rush, take your time.','不要着急，慢慢来。'],
['sad','sæd','adj.','悲伤的','Why are you so sad?','你为什么这么悲伤？'],
['safe','seɪf','adj.','安全的','Is it safe to swim here?','在这里游泳安全吗？'],
['safety','ˈseɪfti','n.','安全','Safety comes first.','安全第一。'],
['sail','seɪl','v.','航行','We sailed across the sea.','我们航行穿过了大海。'],
['salad','ˈsæləd','n.','沙拉','I want a fruit salad.','我想要一份水果沙拉。'],
['sale','seɪl','n.','销售;特卖','The house is for sale.','这房子在出售。'],
['salt','sɔːlt','n.','盐','Please pass me the salt.','请把盐递给我。'],
['same','seɪm','adj.','相同的','We have the same idea.','我们有相同的想法。'],
['sand','sænd','n.','沙子','Children play in the sand.','孩子们在沙子里玩。'],
['sandwich','ˈsænwɪtʃ','n.','三明治','I had a sandwich for lunch.','我午餐吃了一个三明治。'],
['satisfy','ˈsætɪsfaɪ','v.','使满意','The answer satisfied everyone.','答案让所有人都满意了。'],
['save','seɪv','v.','拯救;节省','Save water, save life.','节约用水，拯救生命。'],
['say','seɪ','v.','说','What did you say?','你说了什么？'],
['scared','skerd','adj.','害怕的','I am scared of snakes.','我害怕蛇。'],
['scarf','skɑːrf','n.','围巾','She wears a red scarf.','她戴着一条红围巾。'],
['school','skuːl','n.','学校','I go to school by bus.','我坐公交去上学。'],
['science','ˈsaɪəns','n.','科学','Science is very interesting.','科学非常有趣。'],
['score','skɔːr','n.','分数;得分','What was your test score?','你考试得了多少分？'],
['screen','skriːn','n.','屏幕','Look at the computer screen.','看电脑屏幕。'],
['sea','siː','n.','海','We swam in the sea.','我们在海里游泳。'],
['search','sɜːrtʃ','v.','搜索','Search for the answer online.','在线搜索答案。'],
['season','ˈsiːzn','n.','季节','Spring is my favorite season.','春天是我最喜欢的季节。'],
['seat','siːt','n.','座位','Please take a seat.','请坐。'],
['second','ˈsekənd','num./n.','第二;秒','Wait a second, please.','请等一下。'],
['secret','ˈsiːkrət','n./adj.','秘密','Can you keep a secret?','你能保守秘密吗？'],
['see','siː','v.','看见','I can see the mountain.','我能看见那座山。'],
['seem','siːm','v.','似乎;好像','You seem very happy today.','你今天似乎很开心。'],
['seldom','ˈseldəm','adv.','很少','I seldom watch TV.','我很少看电视。'],
['sell','sel','v.','卖','They sell fresh fruit.','他们卖新鲜水果。'],
['send','send','v.','发送;寄','Send me an email.','给我发一封邮件。'],
['sense','sens','n.','感觉;意义','Common sense is important.','常识很重要。'],
['sentence','ˈsentəns','n.','句子','Make a sentence with this word.','用这个词造句。'],
['separate','ˈsepəreɪt','v.','分开','Separate the good ones from the bad.','把好的和坏的分开。'],
['serious','ˈsɪriəs','adj.','严肃的;严重的','Is it a serious problem?','这是个严重的问题吗？'],
['serve','sɜːrv','v.','服务','How can I serve you?','我能为您做什么？'],
];

let wi = 0;
function nextW() { const w = wb[wi % wb.length]; wi++; return w; }
function wc(n,w) {
  return `<div style="display:flex;align-items:baseline;gap:8px;padding:6px 0;border-bottom:1px solid #eee;font-size:13px"><span style="color:#999;min-width:24px;font-size:11px">${n}.</span><b style="color:#1d1d1f;min-width:80px">${w[0]}</b> <span style="color:var(--sub);font-size:12px;min-width:100px">${w[1]}</span> <span style="color:var(--green);min-width:30px"><i>${w[2]}</i></span> ${w[3]} <button onclick="speak('${w[0]}')" style="border:none;background:var(--blue);color:#fff;border-radius:50%;width:22px;height:22px;cursor:pointer;font-size:10px;flex-shrink:0" title="播放发音">▶</button></div>`;
}
function gray30() {
  let s = '';
  for (let i=1;i<=30;i++) { const w = nextW(); s += wc(i,w) + `<div style="font-size:11px;color:#888;margin-left:122px;margin-bottom:2px">${w[4]} <span style="color:#999">${w[5]}</span></div>\n`; }
  return `<div style="background:#f0f0f5;border-radius:10px;padding:12px 16px;margin:10px 0;border:1px solid #e5e5ea">
<p style="margin:0 0 8px 0"><b>今日30词</b>（点击 ▶ 按钮听发音）</p>
${s}</div>`;
}

// ─── Extract CSS+header from w1.html (safely) ───
const w1src = fs.readFileSync('w1.html','utf8');
const bodyIdx = w1src.indexOf('<body>');
const w1css = bodyIdx > 0 ? w1src.slice(0, bodyIdx + 6) : w1src.slice(0, w1src.indexOf('<nav>'));
const src = fs.readFileSync('guct.html','utf8');

// ─── NO WORD REPLACEMENT - pass through guct.html as-is ───
const processed = src;

// ─── Split by week markers ───
const wkMarkers = [...processed.matchAll(/<div class="week-marker" id="(w\d)">/g)];
const wkContent = {};

for (let i = 0; i < wkMarkers.length; i++) {
  const start = wkMarkers[i].index;
  const end = i < wkMarkers.length - 1 ? wkMarkers[i + 1].index : processed.lastIndexOf('</body>');
  wkContent[wkMarkers[i][1]] = processed.slice(start, end);
}

const wkLabels = {
  w2: {label:'📅 第二周（7月8日-14日）', note:'主题：几何入门+全等三角形 · 每天学习时间 4h（数学2h + 物理1h + 英语1h）'},
  w3: {label:'📅 第三周（7月15日-21日）', note:'主题：函数入门+力学深化 · 每天学习时间 5h（数学2h + 物理1h + 英语1h + 语文1h）'},
  w4: {label:'📅 第四周（7月22日-28日）', note:'主题：几何综合+化学启蒙 · 每天学习时间 5h（数学2h + 物理1h + 化学1h + 英语/语文交替1h）'},
  w5: {label:'📅 第五周（7月29日-8月4日）', note:'主题：几何证明强化+化学元素 · 每天学习时间 5.5h'},
  w6: {label:'📅 第六周（8月5日-11日）', note:'主题：函数提高+力学综合 · 每天学习时间 5h（数学2h + 物理1h + 英语1h + 语文1h）'},
  w7: {label:'📅 第七周（8月12日-18日）', note:'主题：中考真题实战 · 每天学习时间 5.5h（真题模拟3-4h + 错题分析1-2h）'},
  w8: {label:'📅 第八周（8月19日-25日）', note:'主题：初三新课预习 · 每天学习时间 5h（数学2h + 物理/化学交替1h + 英语1h + 语文1h）'},
  w9: {label:'📅 第九周（8月26日-29日）', note:'主题：收尾冲刺 · 错题清零+开学准备 · 每天学习时间 4h'},
};

function makeNav(currentW) {
  const weeks = ['w1','w2','w3','w4','w5','w6','w7','w8','w9'];
  const labels = ['第一周','第二周','第三周','第四周','第五周','第六周','第七周','第八周','第九周'];
  let links = '';
  for (let i = 0; i < weeks.length; i++) {
    const active = weeks[i] === currentW;
    links += `<a href="${weeks[i]}.html" style="padding:6px 10px;border-radius:8px;text-decoration:none;font-weight:600;font-size:11px;background:${active?'var(--blue)':'#e5e5ea'};color:${active?'#fff':'#666'}">${labels[i]}</a>`;
  }
  return `<nav>
<div style="max-width:1000px;margin:0 auto;display:flex;align-items:center;gap:8px;padding:0 16px;flex-wrap:wrap">
<span class="title">📚 暑假逆袭计划</span>
<div style="display:flex;gap:4px;flex-wrap:wrap;align-items:center">${links}<a href="kaogang.html" style="padding:6px 10px;border-radius:8px;text-decoration:none;font-weight:600;font-size:11px;background:#e5e5ea;color:#666">🧠 考纲</a></div>
<a href="index.html" style="font-size:12px;color:var(--sub);text-decoration:none;margin-left:auto">📋 总览</a>
</div>
</nav>`;
}

const script = w1src.match(/(<script>\s*function speak[\s\S]*?<\/script>)/)?.[1] || '<script>function speak(text){if(window.speechSynthesis){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=0.75;window.speechSynthesis.speak(u);}}function showAns(btn){btn.nextElementSibling.classList.toggle("show");}</script>';

for (const wid of ['w2','w3','w4','w5','w6','w7','w8','w9']) {
  const wl = wkLabels[wid];
  let c = wkContent[wid] || '';
  // Remove HTML comments only
  c = c.replace(/<!--[^-]+-->/g, '');
  // Fix week marker: keep content, just fix the header text and id
  c = c.replace(
    /<div class="week-marker" id="w\d">/,
    `<div class="week-marker" id="${wid}">`
  );
  c = c.replace(
    /📅 第[一二三四五六七八九]周（[^）]*）|<div class="wnote">[^<]*/,
    (m) => {
      if (m.startsWith('📅')) return wl.label;
      return `<div class="wnote">${wl.note}`;
    }
  );
  // Inject word lists into English sections that don't have them
  let c2 = c;
  // Find day-page blocks
  const dayRe = /<div class="day-page">/g;
  let dayMatch;
  const dayStarts = [];
  while ((dayMatch = dayRe.exec(c2)) !== null) {
    dayStarts.push(dayMatch.index);
  }
  
  // Process days in reverse to avoid position shifts
  for (let di = dayStarts.length - 1; di >= 0; di--) {
    const ds = dayStarts[di];
    const de = di < dayStarts.length - 1 ? dayStarts[di + 1] : c2.length;
    const day = c2.slice(ds, de);
    
    // Check if this day has English but no word list
    if (day.includes('英语') && !day.includes('今日30词')) {
      // Find insertion point: before <div class="check"> or before closing </div></div>
      let insertPos;
      const checkIdx = day.indexOf('<div class="check">');
      if (checkIdx > 0) {
        insertPos = ds + checkIdx;
      } else {
        // Find the last </div></div> before day end
        const lastDD = day.lastIndexOf('</div></div>');
        insertPos = lastDD > 0 ? ds + lastDD : de - 12;
      }
      
      const wordBlock = '\n' + gray30() + '\n';
      c2 = c2.slice(0, insertPos) + wordBlock + c2.slice(insertPos);
    }
  }
  c = c2;
  const out = w1css + '\n' + makeNav(wid) + '\n\n<div class="container">\n' + c + '\n</div>\n' + script + '\n\n</body>\n</html>';
  fs.writeFileSync(`${wid}.html`, out, 'utf8');
  const wc = (c.match(/今日30词/g) || []).length;
  const gc = (c.match(/background:#f0f0f5/g) || []).length;
  console.log(`${wid}.html: ${out.length}B, words=${wc}, gray=${gc}`);
}
console.log('\nDone!');
