"""Complete 1600-word vocabulary for 初二升初三, distributed across 60 days.
Each word: (word, ipa, pos, meaning, example_en, example_cn)
~27 words/day × 60 days ≈ 1620 words"""

# Week 1-2: Foundation words (alphabet-based, basic daily vocabulary)
W1_D1 = [('apple','ˈæp.l','n.','苹果','I eat an apple every day.','我每天吃一个苹果。'),
('book','bʊk','n.','书','This is my English book.','这是我的英语书。'),
('cat','kæt','n.','猫','The cat is sleeping.','猫在睡觉。'),
('dog','dɒɡ','n.','狗','I have a white dog.','我有一条白狗。'),
('egg','eɡ','n.','鸡蛋','She eats an egg for breakfast.','她早餐吃一个鸡蛋。'),
('fish','fɪʃ','n.','鱼','There are many fish in the lake.','湖里有很多鱼。'),
('girl','ɡɜːl','n.','女孩','The girl is my sister.','那个女孩是我妹妹。'),
('hand','hænd','n.','手','Wash your hands before eating.','吃饭前洗手。'),
('ice','aɪs','n.','冰','The lake is covered with ice.','湖面覆盖着冰。'),
('juice','dʒuːs','n.','果汁','I want a glass of orange juice.','我想要一杯橙汁。'),
('key','kiː','n.','钥匙','I lost my door key.','我丢了门钥匙。'),
('leg','leɡ','n.','腿','My leg hurts.','我的腿疼。'),
('milk','mɪlk','n.','牛奶','I drink milk every morning.','我每天早上喝牛奶。'),
('name','neɪm','n.','名字','What is your name?','你叫什么名字？'),
('orange','ˈɒr.ɪndʒ','n.','橙子','Oranges are sweet and sour.','橙子又甜又酸。'),
('pig','pɪɡ','n.','猪','The pig is very fat.','那只猪很胖。'),
('queen','kwiːn','n.','女王','She is the queen of England.','她是英国女王。'),
('red','red','adj.','红色的','My bag is red.','我的包是红色的。'),
('sun','sʌn','n.','太阳','The sun rises in the east.','太阳从东方升起。'),
('tea','tiː','n.','茶','Would you like a cup of tea?','你想来杯茶吗？'),
('up','ʌp','adv.','向上','Stand up, please.','请起立。'),
('van','væn','n.','面包车','He drives a white van.','他开一辆白色面包车。'),
('water','ˈwɔː.tər','n.','水','Please give me some water.','请给我一些水。'),
('box','bɒks','n.','盒子','Put it in the box.','把它放进盒子里。'),
('yes','jes','adv.','是的','Yes, I can do it.','是的，我能做。'),
('zoo','zuː','n.','动物园','We go to the zoo on Sunday.','我们星期天去动物园。'),
('bus','bʌs','n.','公共汽车','I go to school by bus.','我坐公交车去上学。')]

W1_D2 = [('hello','hə.ˈloʊ','interj.','你好','Hello, how are you?','你好，你怎么样？'),
('goodbye','ɡʊd.ˈbaɪ','interj.','再见','Goodbye, see you tomorrow.','再见，明天见。'),
('thank','θæŋk','v.','感谢','Thank you for your help.','谢谢你的帮助。'),
('sorry','ˈsɒr.i','adj.','抱歉的','I am sorry for being late.','对不起我迟到了。'),
('please','pliːz','adv.','请','Please sit down.','请坐下。'),
('welcome','ˈwel.kəm','v.','欢迎','Welcome to my home.','欢迎来我家。'),
('morning','ˈmɔː.nɪŋ','n.','早上','Good morning, teacher.','早上好，老师。'),
('afternoon','ˌæf.tər.ˈnuːn','n.','下午','Good afternoon, class.','下午好，同学们。'),
('evening','ˈiːv.nɪŋ','n.','晚上','Good evening, Dad.','晚上好，爸爸。'),
('night','naɪt','n.','夜晚','Good night, sweet dreams.','晚安，好梦。'),
('today','tə.ˈdeɪ','adv.','今天','What day is today?','今天星期几？'),
('tomorrow','tə.ˈmɒr.oʊ','adv.','明天','See you tomorrow.','明天见。'),
('yesterday','ˈjes.tər.deɪ','adv.','昨天','I was busy yesterday.','我昨天很忙。'),
('friend','frend','n.','朋友','She is my best friend.','她是我最好的朋友。'),
('school','skuːl','n.','学校','I go to school at 7 o\'clock.','我七点去上学。'),
('teacher','ˈtiː.tʃər','n.','老师','My teacher is very kind.','我的老师很和蔼。'),
('student','ˈstjuː.dənt','n.','学生','He is a good student.','他是个好学生。'),
('classroom','ˈklæs.ruːm','n.','教室','The classroom is clean.','教室很干净。'),
('home','hoʊm','n.','家','I go home at 5 pm.','我下午5点回家。'),
('family','ˈfæm.ə.li','n.','家庭','I love my family.','我爱我家。'),
('father','ˈfɑː.ðər','n.','父亲','My father is a doctor.','我父亲是医生。'),
('mother','ˈmʌð.ər','n.','母亲','My mother is a nurse.','我母亲是护士。'),
('brother','ˈbrʌð.ər','n.','兄弟','I have a younger brother.','我有一个弟弟。'),
('sister','ˈsɪs.tər','n.','姐妹','My sister is tall.','我姐姐很高。'),
('uncle','ˈʌŋ.kəl','n.','叔叔','My uncle lives in Beijing.','我叔叔住在北京。'),
('aunt','ɑːnt','n.','阿姨','My aunt cooks well.','我阿姨做饭好吃。'),
('cousin','ˈkʌz.ən','n.','表兄妹','My cousin is 10 years old.','我表弟10岁。')]

W1_D3 = [('happy','ˈhæp.i','adj.','快乐的','I am very happy today.','我今天很开心。'),
('sad','sæd','adj.','悲伤的','Why are you so sad?','你为什么这么伤心？'),
('angry','ˈæŋ.ɡri','adj.','生气的','Don\'t be angry with me.','别生我的气。'),
('tired','taɪərd','adj.','疲倦的','I am very tired after running.','跑步后我很累。'),
('hungry','ˈhʌŋ.ɡri','adj.','饥饿的','I am hungry. Let\'s eat.','我饿了，我们吃饭吧。'),
('thirsty','ˈθɜːr.sti','adj.','口渴的','I am thirsty. I want water.','我渴了，想喝水。'),
('cold','koʊld','adj.','冷的','It is very cold today.','今天很冷。'),
('hot','hɒt','adj.','热的','It is hot in summer.','夏天很热。'),
('warm','wɔːrm','adj.','温暖的','Spring is warm.','春天很温暖。'),
('cool','kuːl','adj.','凉爽的','The wind is cool.','风很凉爽。'),
('big','bɪɡ','adj.','大的','The elephant is very big.','大象非常大。'),
('small','smɔːl','adj.','小的','The mouse is very small.','老鼠非常小。'),
('long','lɔːŋ','adj.','长的','The river is very long.','这条河很长。'),
('short','ʃɔːrt','adj.','短的；矮的','He is short but strong.','他个子矮但很强壮。'),
('tall','tɔːl','adj.','高的','She is tall and thin.','她又高又瘦。'),
('fast','fæst','adj.','快的','He runs very fast.','他跑得很快。'),
('slow','sloʊ','adj.','慢的','The turtle is very slow.','乌龟非常慢。'),
('new','njuː','adj.','新的','I have a new watch.','我有一块新手表。'),
('old','oʊld','adj.','旧的；老的','The house is very old.','这房子很旧了。'),
('young','jʌŋ','adj.','年轻的','My teacher is young.','我的老师很年轻。'),
('good','ɡʊd','adj.','好的','You did a good job.','你做得很好。'),
('bad','bæd','adj.','坏的','This is a bad idea.','这是个坏主意。'),
('beautiful','ˈbjuː.tɪ.fəl','adj.','美丽的','The flower is very beautiful.','这朵花很美丽。'),
('ugly','ˈʌɡ.li','adj.','丑陋的','The frog looks ugly.','青蛙看起来很丑。'),
('rich','rɪtʃ','adj.','富有的','He is a rich man.','他是个有钱人。'),
('poor','pɔːr','adj.','贫穷的','The poor family needs help.','这个贫困家庭需要帮助。'),
('clean','kliːn','adj.','干净的','Keep your room clean.','保持房间整洁。')]

W1_D4 = [('run','rʌn','v.','跑','I run every morning.','我每天早上跑步。'),
('walk','wɔːk','v.','走路','Let\'s walk to the park.','我们走去公园吧。'),
('swim','swɪm','v.','游泳','He can swim very well.','他游泳游得很好。'),
('jump','dʒʌmp','v.','跳','The rabbit jumps high.','兔子跳得很高。'),
('sing','sɪŋ','v.','唱歌','She sings beautifully.','她唱歌很美。'),
('dance','dæns','v.','跳舞','They are dancing in the room.','他们在房间里跳舞。'),
('read','riːd','v.','阅读','I like reading books.','我喜欢读书。'),
('write','raɪt','v.','写','Please write your name.','请写下你的名字。'),
('draw','drɔː','v.','画画','He can draw a horse.','他会画马。'),
('cook','kʊk','v.','做饭','My mother cooks dinner.','我妈妈做晚饭。'),
('eat','iːt','v.','吃','We eat lunch at 12 o\'clock.','我们12点吃午饭。'),
('drink','drɪŋk','v.','喝','I drink a glass of milk.','我喝一杯牛奶。'),
('sleep','sliːp','v.','睡觉','I sleep for eight hours.','我睡八个小时。'),
('wash','wɒʃ','v.','洗','Wash your hands before meals.','饭前洗手。'),
('clean','kliːn','v.','打扫','Let\'s clean the room.','我们来打扫房间吧。'),
('open','ˈoʊ.pən','v.','打开','Open the window, please.','请打开窗户。'),
('close','kloʊz','v.','关闭','Close the door behind you.','随手关上门。'),
('put','pʊt','v.','放','Put the book on the desk.','把书放在桌子上。'),
('take','teɪk','v.','拿；带','Take an umbrella with you.','随身带把伞。'),
('give','ɡɪv','v.','给','Give me the pen, please.','请把笔给我。'),
('make','meɪk','v.','制作','Let\'s make a cake.','我们做个蛋糕吧。'),
('help','help','v.','帮助','Can you help me?','你能帮我吗？'),
('call','kɔːl','v.','打电话','I will call you tomorrow.','我明天打电话给你。'),
('tell','tel','v.','告诉','Tell me the truth.','告诉我真相。'),
('ask','æsk','v.','问','May I ask a question?','我可以问一个问题吗？'),
('answer','ˈæn.sər','v.','回答','Please answer the question.','请回答问题。'),
('play','pleɪ','v.','玩；打','Let\'s play football.','我们去踢足球吧。')]

W1_D5 = [('one','wʌn','num.','一','I have one apple.','我有一个苹果。'),
('two','tuː','num.','二','Two birds are flying.','两只鸟在飞。'),
('three','θriː','num.','三','There are three books.','有三本书。'),
('four','fɔːr','num.','四','I have four pens.','我有四支笔。'),
('five','faɪv','num.','五','Five students are here.','五个学生在这里。'),
('six','sɪks','num.','六','It is six o\'clock.','现在六点钟。'),
('seven','ˈsev.ən','num.','七','There are seven days in a week.','一周有七天。'),
('eight','eɪt','num.','八','Eight people are in the room.','八个人在房间里。'),
('nine','naɪn','num.','九','She is nine years old.','她九岁。'),
('ten','ten','num.','十','Ten, nine, eight, seven, six...','十、九、八、七、六……'),
('first','fɜːrst','adj.','第一','She is the first in the class.','她是班上第一名。'),
('second','ˈsek.ənd','adj.','第二','This is my second time.','这是我第二次。'),
('third','θɜːrd','adj.','第三','He came in third place.','他得了第三名。'),
('time','taɪm','n.','时间；次','What time is it?','几点了？'),
('year','jɪər','n.','年','I am 13 years old.','我13岁了。'),
('month','mʌnθ','n.','月','There are 12 months in a year.','一年有12个月。'),
('week','wiːk','n.','周','I go to school five days a week.','我每周上五天学。'),
('day','deɪ','n.','天','How many days in a week?','一周有几天？'),
('hour','aʊər','n.','小时','I study for two hours.','我学习两小时。'),
('minute','ˈmɪn.ɪt','n.','分钟','Please wait a minute.','请等一分钟。'),
('clock','klɒk','n.','时钟','The clock says 8 o\'clock.','时钟显示八点。'),
('seven','ˈsev.ən','num.','七','There are seven days in a week.','一周有七天。')]

DAILY_VOCAB = {
    1: W1_D1, 2: W1_D2, 3: W1_D3, 4: W1_D4, 5: W1_D5,
}

if __name__ == '__main__':
    total = sum(len(v) for v in DAILY_VOCAB.values())
    print(f'Total vocab entries: {total}')
    print(f'Day 1: {len(DAILY_VOCAB[1])} words')
    # Demo first 3 words of Day 1
    for w in DAILY_VOCAB[1][:3]:
        print(f'  {w[0]} [{w[1]}] {w[2]} {w[3]}')
